set1 = set("helloforhello")
print(set1)
list = ["hello", "for", "hello"]
set2 = set(list)
print(set2)
set1.add("hell")
set1.add("or")
set1.add("heaven")
print(set1)
set1.remove("hell")
set1.remove("or")
set1.remove("heaven")
print(set1)
for i in range(5):
    set1.discard(i)
print(set1)
set1.pop()
print(set1)