import operator
a = 4
b = 2
print("1")
print(operator.add(a,b))
print("2")
print(operator.sub(a,b))
print("3")
print(operator.mul(a,b))
print("4")
print(operator.add(a,b))
print("5")
print(operator.truediv(a,b))
print("6")
print(operator.floordiv(a,b))
print("7")
print(operator.pow(a,b))
print("8")
print(operator.mod(a,b))
print("9")
print(operator.lt(a,b))
print("10")
print(operator.le(a,b))
print("12")
print(operator.eq(a,b))
print("12")
print(operator.ne(a,b))
print("13")
print(operator.gt(a,b))
print("14")
print(operator.ge(a,b))